# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_position_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 374)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.firstNameLabel = QtWidgets.QLabel(Dialog)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.firstNameLabel)
        self.lblFirstName = QtWidgets.QLabel(Dialog)
        self.lblFirstName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFirstName.setObjectName("lblFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblFirstName)
        self.lastNameLabel = QtWidgets.QLabel(Dialog)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
        self.lblLastName = QtWidgets.QLabel(Dialog)
        self.lblLastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLastName.setObjectName("lblLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblLastName)
        self.currentPositionLabel = QtWidgets.QLabel(Dialog)
        self.currentPositionLabel.setObjectName("currentPositionLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.currentPositionLabel)
        self.lblCurrentPosition = QtWidgets.QLabel(Dialog)
        self.lblCurrentPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentPosition.setObjectName("lblCurrentPosition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblCurrentPosition)
        self.newPositionLabel = QtWidgets.QLabel(Dialog)
        self.newPositionLabel.setObjectName("newPositionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.newPositionLabel)
        self.lineEditNewPosition = QtWidgets.QLineEdit(Dialog)
        self.lineEditNewPosition.setPlaceholderText("")
        self.lineEditNewPosition.setObjectName("lineEditNewPosition")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditNewPosition)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)


        Dialog.setStyleSheet("""
            QDialog {
                background-color: rgb(55, 64, 88);
            }

            QLabel {
                color: white;
                font-size: 10pt;
                font-family: Verdana;
            }

            QPushButton {
                color: white;
                border-radius: 10px;
                padding-left: 10px;
                padding-right: 10px;
                padding-top: 4px;
                padding-bottom: 4px;
                background-color: rgb(90, 90, 90);

            }
        """)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.firstNameLabel.setText(_translate("Dialog", "First Name"))
        self.lblFirstName.setText(_translate("Dialog", "Peter"))
        self.lastNameLabel.setText(_translate("Dialog", "Last Name"))
        self.lblLastName.setText(_translate("Dialog", "Tan"))
        self.currentPositionLabel.setText(_translate("Dialog", "Current Position"))
        self.lblCurrentPosition.setText(_translate("Dialog", "Placeholder Position"))
        self.newPositionLabel.setText(_translate("Dialog", "New Position"))
        self.saveButton.setText(_translate("Dialog", "Save"))




class PositionDialog(QtWidgets.QDialog):

    def __init__(self, first_name, last_name, current_position):
        super(PositionDialog, self).__init__()

        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        self.ui.lblFirstName.setText(first_name)
        self.ui.lblLastName.setText(last_name)
        self.ui.lblCurrentPosition.setText(current_position)

        self.ui.saveButton.clicked.connect(self.save_button_clicked)


    def save_button_clicked(self):
        self.new_position = self.ui.lineEditNewPosition.text()

        self.accept()
